---
apiVersion: v1
data:
  TZ: @timezone@
kind: ConfigMap
metadata:
  labels:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant-config-extraconf
  namespace: @namespace@
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant
  namespace: @namespace@
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "home-assistant"
    tailscale.com/tags: "tag:http"
spec:
  ports:
  - name: http
    port: @port@
    protocol: TCP
    targetPort: http
  selector:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homekit-bridge
  name: homekit-bridge
  namespace: @namespace@
spec:
  ports:
  - name: homekit-bridge
    port: 32000
    protocol: TCP
    targetPort: 32000
    nodePort: 32000
  selector:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant
  namespace: @namespace@
spec:
  replicas: @replicas@
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: home-assistant
      app.kubernetes.io/name: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-assistant
        app.kubernetes.io/name: home-assistant
    spec:
      nodeSelector:
        kubernetes.io/hostname: @nodename@
      containers:
      - envFrom:
        - configMapRef:
            name: home-assistant-config-extraconf
        image: @image@
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        name: home-assistant-app
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - SYS_ADMIN
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
        - containerPort: 32000
          name: homekit-bridge
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        resources: {}
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 0
          periodSeconds: 5
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /config
          name: ha-config-root
          # Bluetooth
        - mountPath: /dev/ttyACM0
          name: ttyacm
        - mountPath: /run/dbus
          name: dbus
        - mountPath: /dev/ttyUSB0
          name: ttyusb
      restartPolicy: Always
      volumes:
      - name: ha-config-root
        hostPath:
          path: @hostfolder@
          type: DirectoryOrCreate
      # Bluetooth
      - name: ttyacm
        hostPath:
          path: /dev/ttyACM0
      # Zigbee USB
      - name: ttyusb
        hostPath:
          path: /dev/ttyUSB0
      - name: dbus
        hostPath:
          path: /run/dbus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: matter-server
  name: matter-server
  namespace: @namespace@
spec:
  replicas: @replicas@
  selector:
    matchLabels:
      app: matter-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      hostNetwork: true
      containers:
        - env:
            - name: TZ
              value: "@timezone@"
          image: @matter_image@
          ports:
            - containerPort: 5580
              protocol: TCP
          name: matter-server
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
          volumeMounts:
            - mountPath: /data
              name: matter-data
      restartPolicy: Always
      volumes:
        - name: matter-data
          hostPath:
            path: @hostfolder@/matter-server
            type: DirectoryOrCreate
        # Bluetooth
        - name: ttyacm
          hostPath:
            path: /dev/ttyACM0
        # Zigbee USB
        - name: ttyusb
          hostPath:
            path: /dev/ttyUSB0
        - name: dbus
          hostPath:
            path: /run/dbus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: matter-server
  name: matter-server
  namespace: @namespace@
spec:
  ports:
    - name: "matter-websocket"
      port: 5580
      targetPort: 5580
  selector:
    app: matter-server
