---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: db
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: postgres:16-alpine
          livenessProbe:
            exec:
              command:
                - pg_isready -U learnhouse
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 4
          name: learnhouse-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: learnhouse-db-data
      restartPolicy: Always
      volumes:
        - name: learnhouse-db-data
          persistentVolumeClaim:
            claimName: learnhouse-db-data
---
apiVersion: v1
data:
  HTTP_PORT: "80"
  LEARNHOUSE_AUTH_JWT_SECRET_KEY: changeme
  LEARNHOUSE_CONTENT_DELIVERY_TYPE: filesystem
  LEARNHOUSE_COOKIE_DOMAIN: .localhost
  LEARNHOUSE_DEVELOPMENT_MODE: "False"
  LEARNHOUSE_DOMAIN: localhost
  LEARNHOUSE_INITIAL_ADMIN_EMAIL: admin@school.dev
  LEARNHOUSE_INITIAL_ADMIN_PASSWORD: your-secure-password-here
  LEARNHOUSE_IS_AI_ENABLED: "False"
  LEARNHOUSE_LOGFIRE_ENABLED: "False"
  LEARNHOUSE_PORT: "9000"
  LEARNHOUSE_REDIS_CONNECTION_STRING: redis://redis:6379/learnhouse
  LEARNHOUSE_SQL_CONNECTION_STRING: postgresql://learnhouse:learnhouse@db:5432/learnhouse
  NEXT_PUBLIC_LEARNHOUSE_API_URL: http://localhost/api/v1/
  NEXT_PUBLIC_LEARNHOUSE_BACKEND_URL: http://localhost/
  NEXT_PUBLIC_LEARNHOUSE_DEFAULT_ORG: default
  NEXT_PUBLIC_LEARNHOUSE_DOMAIN: localhost
  NEXT_PUBLIC_LEARNHOUSE_HTTPS: "False"
  NEXT_PUBLIC_LEARNHOUSE_MULTI_ORG: "False"
  NEXT_PUBLIC_LEARNHOUSE_TOP_DOMAIN: localhost
  NEXTAUTH_SECRET: changeme
  NEXTAUTH_URL: http://localhost
  POSTGRES_DB: learnhouse
  POSTGRES_PASSWORD: learnhouse
  POSTGRES_USER: learnhouse
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: db-env
  name: env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: learnhouse-app
  name: learnhouse-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: learnhouse-app
  template:
    metadata:
      labels:
        io.kompose.service: learnhouse-app
    spec:
      containers:
        - env:
            - name: HOSTNAME
              value: 0.0.0.0
          envFrom:
            - configMapRef:
                name: env
          image: ghcr.io/learnhouse/app:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost/api/v1/health
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          name: learnhouse-app
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: learnhouse-db-data
  name: learnhouse-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: learnhouse-redis-data
  name: learnhouse-redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
data:
  nginx.prod.conf: "\nserver {\n    listen 80;\n    server_name _;\n    client_max_body_size 500M;\n\n    # Increase header buffer size\n    large_client_header_buffers 4 32k;\n\n    # Increase the maximum allowed size of the client request body\n    client_body_buffer_size 32k;\n\n    # Increase the maximum allowed size of the client request header fields\n    client_header_buffer_size 32k;\n\n    # Proxy all requests to the learnhouse-app service\n    # The app container has internal nginx routing between frontend and backend\n    location / {\n        proxy_pass http://learnhouse-app:80;\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto $scheme;\n        \n        # WebSocket support\n        proxy_http_version 1.1;\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection \"upgrade\";\n        \n        # Timeouts for long-running requests\n        proxy_read_timeout 300s;\n        proxy_connect_timeout 75s;\n    }\n}"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: nginx
  name: nginx-cm0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: nginx:alpine
          livenessProbe:
            exec:
              command:
                - wget --quiet --tries=1 --spider http://localhost/ || exit 1
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: learnhouse-nginx
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-cm0
              readOnly: true
              subPath: default.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: nginx.prod.conf
                path: default.conf
            name: nginx-cm0
          name: nginx-cm0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - args:
            - redis-server
            - --appendonly
            - "yes"
          image: redis:7.2.3-alpine
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 4
          name: learnhouse-redis
          volumeMounts:
            - mountPath: /data
              name: learnhouse-redis-data
      restartPolicy: Always
      volumes:
        - name: learnhouse-redis-data
          persistentVolumeClaim:
            claimName: learnhouse-redis-data
