---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/instance: minecraft
  name: minecraft
  namespace: @namespace@
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: minecraft-clusterrolebinding
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/instance: minecraft
subjects:
  - kind: ServiceAccount
    name: minecraft
    namespace: @namespace@
roleRef:
  kind: ClusterRole
  name: minecraft-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minecraft
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/instance: minecraft
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minecraft
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/instance: minecraft
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minecraft
subjects:
- kind: ServiceAccount
  name: minecraft
  namespace: @namespace@
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock
  namespace: @namespace@
  labels:
    app: minecraft-bedrock
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "minecraft"
    tailscale.com/tags: "tag:minecraft"
spec:
  type: ClusterIP
  ports:
  - name: minecraft
    port: 19132
    targetPort: 19132
    protocol: UDP
  selector:
    app: minecraft-bedrock
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-manager
  namespace: @namespace@
  labels:
    app: minecraft-bedrock
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "minecraft-manager"
    tailscale.com/tags: "tag:http"
spec:
  type: ClusterIP
  ports:
  - name: manager
    port: 80
    targetPort: manager
  selector:
    app: minecraft-bedrock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bedrock
  namespace: @namespace@
  labels:
    app: minecraft-bedrock
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft-bedrock
  template:
    metadata:
      labels:
        app: minecraft-bedrock
    spec:
      serviceAccountName: minecraft
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: minecraft-bedrock
        image: "@image@"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        ports:
        - name: minecraft
          containerPort: 19132
          protocol: UDP
        - name: manager
          containerPort: 11325
          protocol: TCP
        volumeMounts:
        - name: configdir
          mountPath: /root/.config/bedrock-server-manager
        - name: datadir
          mountPath: /root/bedrock-server-manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: tmp
        emptyDir: {}
      - name: configdir
        hostPath:
          path: @hostfolder@/config
          type: DirectoryOrCreate
      - name: datadir
        hostPath:
          path: @hostfolder@/data
          type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: @nodename@
