---
apiVersion: v1
kind: Service
metadata:
  name: tor-socks-proxy
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: tor-socks-proxy
    app.kubernetes.io/instance: tor-socks-proxy
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "tor"
    tailscale.com/tags: "tag:socks,tag:dns"
spec:
  type: ClusterIP
  ports:
    - port: 1080
      targetPort: socks
      protocol: TCP
      name: tor-socks-proxy
    - port: 53
      targetPort: dns
      protocol: TCP
      name: tor-socks-dns
  selector:
    app.kubernetes.io/name: tor-socks-proxy
    app.kubernetes.io/instance: tor-socks-proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tor-socks-proxy-torrc
  namespace: @namespace@
data:
  torrc: |
    HardwareAccel 1
    Log notice stdout
    DNSPort 0.0.0.0:8853
    SocksPort 0.0.0.0:9150
    DataDirectory /var/lib/tor
    EntryNodes {US} StrictNodes 1
    ExitNodes {US} StrictNodes 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor-socks-proxy
  namespace: @namespace@
  labels:
    app.kubernetes.io/name: tor-socks-proxy
    app.kubernetes.io/instance: tor-socks-proxy
spec:
  replicas: @replicas@
  selector:
    matchLabels:
      app.kubernetes.io/name: tor-socks-proxy
      app.kubernetes.io/instance: tor-socks-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tor-socks-proxy
        app.kubernetes.io/instance: tor-socks-proxy
    spec:
      securityContext:
        {}
      containers:
        - name: tor-socks-proxy
          securityContext:
            {}
          image: "@image@"
          imagePullPolicy: IfNotPresent
          ports:
            - name: socks
              containerPort: 9150
              protocol: TCP
            - name: dns
              containerPort: 8853
              protocol: UDP
          volumeMounts:
            - name: torrc
              mountPath: /etc/tor/torrc
              subPath: torrc
          resources:
            {}
      volumes:
        - name: torrc
          configMap:
            name: tor-socks-proxy-torrc
