---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: android
    app.kubernetes.io/instance: android
  name: android
  namespace: machine-learning
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: android-clusterrolebinding
  labels:
    app.kubernetes.io/name: android
    app.kubernetes.io/instance: android
subjects:
  - kind: ServiceAccount
    name: android
    namespace: machine-learning
roleRef:
  kind: ClusterRole
  name: android-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: android
  namespace: machine-learning
  labels:
    app.kubernetes.io/name: android
    app.kubernetes.io/instance: android
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: android
  namespace: machine-learning
  labels:
    app.kubernetes.io/name: android
    app.kubernetes.io/instance: android
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: android
subjects:
- kind: ServiceAccount
  name: android
  namespace: machine-learning
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: android
  namespace: machine-learning
  labels:
    app: android
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: android
  template:
    metadata:
      labels:
        app: android
    spec:
      serviceAccountName: android
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: docker-android-init
        image: docker.io/budtmo/docker-android:emulator_14.0_v3.5.2-p0
        securityContext:
          runAsUser: 0
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "apt update && apt install -y rsync && rsync -a --ignore-existing /home/androidusr/ /new" ]
        volumeMounts:
          - name: android-data
            mountPath: /new
      containers:
      - name: android
        image: "docker.io/budtmo/docker-android:emulator_14.0_v3.5.2-p0"
        securityContext:
          privileged: true # for virtualizing android
        ports:
        - name: android
          containerPort: 6080
          protocol: TCP
        - name: adb
          containerPort: 5555
          protocol: TCP
        env:
          - name: EMULATOR_DEVICE
            value: "Samsung Galaxy S10"
          - name: WEB_VNC
            value: "true"
        volumeMounts:
          - name: android-data
            mountPath: /home/androidusr
      volumes:
        - name: android-data
          hostPath:
            path: /media/data-ssd/android
            type: Directory
      nodeSelector:
        kubernetes.io/hostname: homelab
---
apiVersion: v1
kind: Service
metadata:
  name: adb
  namespace: machine-learning
  labels:
    app: android
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "adb"
    tailscale.com/tags: "tag:adb"
spec:
  type: ClusterIP
  ports:
  - name: android
    port: 5555
    targetPort: adb
    protocol: TCP
  selector:
    app: android
---
apiVersion: v1
kind: Service
metadata:
  name: android
  namespace: machine-learning
  labels:
    app: android
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "android"
    tailscale.com/tags: "tag:http"
spec:
  type: ClusterIP
  ports:
  - name: android
    port: 80
    targetPort: android
    protocol: TCP
  selector:
    app: android
