---
apiVersion: v1
data:
  TZ: America/Denver
kind: ConfigMap
metadata:
  labels:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant-config-extraconf
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant
  namespace: default
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "home-assistant"
    tailscale.com/tags: "tag:home-assistant"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: home-assistant
      app.kubernetes.io/name: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-assistant
        app.kubernetes.io/name: home-assistant
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
      - envFrom:
        - configMapRef:
            name: home-assistant-config-extraconf
        image: ghcr.io/home-assistant/home-assistant:2026.6.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        name: home-assistant-app
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - SYS_ADMIN
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        resources: {}
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 0
          periodSeconds: 5
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /config
          name: ha-config-root
          # Bluetooth
        - mountPath: /dev/ttyACM0
          name: ttyacm
        - mountPath: /run/dbus
          name: dbus
        - mountPath: /dev/ttyUSB0
          name: ttyusb
      restartPolicy: Always
      volumes:
      - name: ha-config-root
        hostPath:
          path: /media/data-ssd/home-assistant
          type: DirectoryOrCreate
      # Bluetooth
      - name: ttyacm
        hostPath:
          path: /dev/ttyACM0
      # Zigbee USB
      - name: ttyusb
        hostPath:
          path: /dev/ttyUSB0
      - name: dbus
        hostPath:
          path: /run/dbus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: matter-server
  name: matter-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matter-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      hostNetwork: true
      containers:
        - env:
            - name: TZ
              value: "America/Denver"
          image: ghcr.io/home-assistant-libs/python-matter-server:8.1
          ports:
            - containerPort: 5580
              protocol: TCP
          name: matter-server
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
          volumeMounts:
            - mountPath: /data
              name: matter-data
      restartPolicy: Always
      volumes:
        - name: matter-data
          hostPath:
            path: /media/data-ssd/home-assistant/matter-server
            type: DirectoryOrCreate
        # Bluetooth
        - name: ttyacm
          hostPath:
            path: /dev/ttyACM0
        # Zigbee USB
        - name: ttyusb
          hostPath:
            path: /dev/ttyUSB0
        - name: dbus
          hostPath:
            path: /run/dbus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: matter-server
  name: matter-server
  namespace: default
spec:
  ports:
    - name: "matter-websocket"
      port: 5580
      targetPort: 5580
  selector:
    app: matter-server
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: "frigate"
  namespace: "default"
spec:
  itemPath: "vaults/Kubernetes/items/5r2mzxzqbozrmctx6qthzqgouy"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frigate
  name: frigate
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      containers:
        - env:
            - name: TZ
              value: "America/Denver"
          image: ghcr.io/blakeblackshear/frigate:stable
          ports:
            - containerPort: 8971
              protocol: TCP
            - containerPort: 8554
              protocol: TCP
            - containerPort: 8555
              protocol: TCP
            - containerPort: 8555
              protocol: UDP
          name: frigate
          volumeMounts:
            - mountPath: /config
              name: frigate-config
            - mountPath: /media/frigate
              name: frigate-storage
            - mountPath: /dev/shm
              name: frigate-shm
            - mountPath: /tmp/cache
              name: frigate-tmpfs
          securityContext:
            privileged: true
          resources:
            requests:
              gpu.intel.com/i915: "1"
            limits:
              gpu.intel.com/i915: "1"
          env:
            - name: FRIGATE_RTSP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: frigate
                  key: rtsp-password
      restartPolicy: Always
      volumes:
        - name: frigate-config
          hostPath:
            path: /media/data-ssd/home-assistant/frigate/config
            type: DirectoryOrCreate
        - name: frigate-storage
          hostPath:
            path: /media/data-ssd/home-assistant/frigate/storage
            type: DirectoryOrCreate
        - name: frigate-shm
          emptyDir:
             medium: Memory
        - name: frigate-tmpfs
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frigate
  name: frigate
  namespace: default
spec:
  ports:
    - name: "frigate"
      port: 80
      targetPort: 8971
    - name: "frigate-rtsp"
      port: 8554
      targetPort: 8554
    - name: "frigate-wrtc"
      port: 8555
      targetPort: 8555
      protocol: TCP
    - name: "frigate-wrtc-udp"
      port: 8555
      targetPort: 8555
      protocol: UDP
  selector:
    app: frigate
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: "eufy"
  namespace: "default"
spec:
  itemPath: "vaults/Kubernetes/items/2bt7kfmjowtpqsvdvqvewn7ase"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eufy
  name: eufy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eufy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eufy
    spec:
      containers:
        - env:
            - name: TZ
              value: "America/Denver"
          image: docker.io/bropat/eufy-security-ws:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          name: eufy
          volumeMounts:
            - mountPath: /data
              name: eufy-data
          env:
            - name: COUNTRY
              value: "US"
            - name: PORT
              value: "3000"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: eufy
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eufy
                  key: password
      restartPolicy: Always
      volumes:
        - name: eufy-data
          hostPath:
            path: /media/data-ssd/home-assistant/eufy
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eufy
  name: eufy
  namespace: default
spec:
  clusterIP: 10.43.9.155
  ports:
    - name: "eufy"
      port: 3000
      targetPort: 3000
  selector:
    app: eufy
