# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usbhid" "uas" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks";
      fsType = "ext4";
    };

  # LUKS partition, Yubikey support
  # See https://nixos.wiki/wiki/Yubikey_based_Full_Disk_Encryption_(FDE)_on_NixOS
  # Setup after initial install with these commands: https://gist.github.com/heywoodlh/4cc0254359b173ba9f9a1ea8f3b2e49f
  boot.initrd = {
    kernelModules = ["vfat" "nls_cp437" "nls_iso8859-1" "usbhid"];
    luks = {
      yubikeySupport = true;
      devices."luks" = {
        device = "/dev/disk/by-uuid/a5764b6d-4435-4dde-97e5-43a3c1738c85";
        yubikey = {
          slot = 2;
          twoFactor = false; # Set to false for 1FA
          gracePeriod = 30; # Time in seconds to wait for Yubikey to be inserted
          keyLength = 64; # Set to $KEY_LENGTH/8
          saltLength = 16; # Set to $SALT_LENGTH
          storage = {
            device = "/dev/nvme0n1p4"; # Unencrypted /boot device
            fsType = "vfat";
            path = "/crypt-storage/default"; # Path relative to /boot
          };
        };
      };
    };
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/32A7-11EA";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
