# Do not modify this file!  It was generated by ‘nixos-generate-config’ and may be overwritten by future invocations.  Please make changes to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usb_storage" "sd_mod" ]; boot.initrd.kernelModules = [ ]; boot.kernelModules = [ "kvm-intel" ]; boot.extraModulePackages = [ ];

  fileSystems."/" = { device = "/dev/disk/by-uuid/9b84f9aa-713c-4751-8e09-e47e6b13af9b";
      fsType = "ext4";
    };

  fileSystems."/boot" = { device = "/dev/disk/by-uuid/E455-2524";
      fsType = "vfat"; options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ {
      device = "/swap"; size = 2 * 1024;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking (the default) this is the recommended approach. When using systemd-networkd it's still possible to use this option, but it's recommended to use it in 
  # conjunction with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true; networking.interfaces.enp2s0.useDHCP = lib.mkDefault true; networking.interfaces.enp3s0.useDHCP = lib.mkDefault true; networking.interfaces.enp4s0.useDHCP = lib.mkDefault true; 
  # networking.interfaces.wlp0s20u5.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux"; hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Enable reverse proxy for immich
  networking.firewall.interfaces = {
    enp1s0.allowedTCPPorts = [
      80
    ];
    tailscale0.allowedTCPPorts = [
      80
    ];
  };
  systemd.services.immich-proxy = {
    enable = true;
    after = [ "network.target" ];
    wantedBy = [ "default.target" ];
    description = "Immich reverse proxy";
    serviceConfig = {
      Type = "simple";
      User = "root";
      ExecStart = ''
        ${pkgs.caddy}/bin/caddy reverse-proxy --disable-redirects --insecure --from :80 --to http://immich.barn-banana.ts.net
      '';
    };
  };

  services.cloudflared = {
    enable = true;
    tunnels = {
      "slc" = {
        default = "http_status:404";
        credentialsFile = "/opt/cloudflared/token";
      };
    };
  };

  environment.systemPackages = with pkgs; [
    cloudflared
  ];

  heywoodlh.rayhunter = {
    enable = true;
    ntfy = "http://ntfy.barn-banana.ts.net";
    user = "rayhunter";
    interface = "enp0s20u2";
    port = 6767;
  };

  heywoodlh.sshd.mfa = true;
}
