# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "uas" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8c976538-fbc3-4e42-9e64-019dc323b166";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8c976538-fbc3-4e42-9e64-019dc323b166".device = "/dev/disk/by-uuid/8c976538-fbc3-4e42-9e64-019dc323b166";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E095-4E6F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
