{
  description = "Jujutsu flake";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  inputs.flake-utils.url = "github:numtide/flake-utils";
  inputs.toml-merge = {
    url = "github:boivie/toml-merge/1.0.0-rc.1";
    flake = false;
  };

  outputs =
    inputs@{
      self,
      nixpkgs,
      flake-utils,
      toml-merge,
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        config-toml = pkgs.writeText "config.toml" ''
          [user]
          name = "Spencer Heywood"
          email = "github@heywoodlh.io"

          [ui]
          editor = "vim"
        '';
        toml-merge-go = pkgs.buildGoModule {
          name = "toml-merge";
          src = toml-merge;
          vendorHash = "sha256-hj1rQJED2llW782lPYYWDD1TgNgHPa0z9nUdj4kWryw=";
          postPatch = ''
            cp ${./go.mod} go.mod
            cp ${./go.sum} go.sum
          '';
        };
      in
      {
        packages = rec {
          jujutsu = pkgs.writeShellScriptBin "jj" ''
            # prioritize local config if exists
            if [[ -e $HOME/.config/jujutsu/config.toml ]]; then
              mkdir -p $HOME/tmp/heywoodlh-jj/
              ${toml-merge-go}/bin/toml-merge ${config-toml} $HOME/.config/jujutsu/config.toml | ${pkgs.gnugrep}/bin/grep -v 'autogenerated' > $HOME/tmp/heywoodlh-jj/config.toml
              export JJ_CONFIG=$HOME/tmp/heywoodlh-jj/config.toml
            else
              export JJ_CONFIG=${config-toml}
            fi
            exec ${pkgs.jujutsu}/bin/jj "$@"
          '';
          toml-merge = toml-merge-go;
          config = config-toml;
          default = jujutsu;
        };

        formatter = pkgs.nixfmt-rfc-style;
      }
    );
}
