---
- name: delete old generations
  ansible.builtin.command: nix-collect-garbage --delete-older-than 7d

- name: run nixos-rebuild against hostname
  ansible.builtin.shell: >
    nixos-rebuild switch --flake "git+https://tangled.org/heywoodlh.io/nixos-configs#$(hostname)" --impure
