{
  config,
  pkgs,
  lib,
  hypr-rdp,
  ...
}:

with lib;

let
  cfg = config.heywoodlh.home.hypr-rdp;
  cargoToml = builtins.fromTOML (builtins.readFile "${hypr-rdp}/Cargo.toml");
  # Upstream's flake pins a stale cargo vendor hash that no longer matches the
  # vendored dependencies, so build the package directly with the correct hash.
  # Also fix the invisible-cursor bug: hypr-rdp calls wlr-screencopy's
  # capture_output with overlay_cursor=0, so the cursor is never composited into
  # captured frames (invisible over RDP). Flip it to 1 so the cursor shows.
  hypr-rdp-pkg = pkgs.rustPlatform.buildRustPackage {
    pname = "hypr-rdp";
    version = cargoToml.package.version;

    src = hypr-rdp;

    cargoHash = "sha256-Ap3TSzOvQ7Fg7w+kUMPV9EZRYPNNg3yIDuC02sULdMQ=";

    nativeBuildInputs = with pkgs; [
      pkg-config
      cmake
      clang
      makeWrapper
      rustPlatform.bindgenHook
    ];

    buildInputs = with pkgs; [
      ffmpeg
      libdrm
      libgbm
      libva
      libxkbcommon
      mesa
      pipewire
      wayland
    ];

    postPatch = ''
      substituteInPlace src/capture/wayland/wlr.rs \
        --replace-fail "capture_output(0," "capture_output(1,"
    '';

    postInstall = ''
      wrapProgram $out/bin/hypr-rdp \
        --prefix PATH : ${lib.makeBinPath [ pkgs.pulseaudio ]}
    '';

    doCheck = false;

    meta = {
      description = cargoToml.package.description;
      homepage = "https://github.com/MuNeNICK/hypr-rdp";
      license = lib.licenses.mit;
      mainProgram = "hypr-rdp";
      platforms = lib.platforms.linux;
    };
  };
  # Interactively generate ~/.config/hypr-rdp/config.toml. hypr-rdp auto-detects
  # the GPU (it scans /dev/dri/renderD* for an H.264-capable VA-API device), so
  # there is no "vendor" to select; instead the encoder is controlled here via
  # the h264_backend key. All settings live in config.toml so they can be tuned
  # per-machine without a rebuild.
  hypr-rdp-setup = pkgs.writeShellScriptBin "hypr-rdp-setup" ''
    set -eu
    config_dir="''${XDG_CONFIG_HOME:-$HOME/.config}/hypr-rdp"
    config_file="$config_dir/config.toml"

    # Default to mirroring the first physical (non-headless) output.
    default_output="$(${pkgs.hyprland}/bin/hyprctl monitors -j 2>/dev/null \
      | ${pkgs.jq}/bin/jq -r 'first(.[] | select((.name | startswith("HEADLESS")) | not) | .name) // empty' 2>/dev/null || true)"

    printf 'Username: '
    read -r username
    printf 'Password: '
    stty -echo
    read -r password
    stty echo
    printf '\n'
    printf 'Bind address [0.0.0.0:3389]: '
    read -r bind
    [ -z "$bind" ] && bind="0.0.0.0:3389"
    printf 'Output to mirror [%s] (empty = headless): ' "$default_output"
    read -r output
    [ -z "$output" ] && output="$default_output"
    printf 'Session resolution [1920x1080] (empty = native output size): '
    read -r resolution
    [ -z "$resolution" ] && resolution="1920x1080"
    printf 'H.264 backend - auto/software/vaapi [auto]: '
    read -r backend
    [ -z "$backend" ] && backend="auto"

    ${pkgs.coreutils}/bin/mkdir -p "$config_dir"
    ${pkgs.coreutils}/bin/install -m 600 /dev/null "$config_file"
    {
      printf 'username = "%s"\n' "$username"
      printf 'password = "%s"\n' "$password"
      printf 'bind = "%s"\n' "$bind"
      [ -n "$output" ] && printf 'output = "%s"\n' "$output"
      [ -n "$resolution" ] && printf 'resolution = "%s"\n' "$resolution"
      printf 'h264_backend = "%s"\n' "$backend"
    } > "$config_file"
    printf 'Wrote %s\n' "$config_file"
  '';
in {
  options.heywoodlh.home.hypr-rdp = mkOption {
    default = {};
    description = ''
      heywoodlh hypr-rdp (RDP server for Hyprland) configuration. When enabled,
      the hypr-rdp server runs as a systemd user service (`hypr-rdp.service`)
      tied to graphical-session.target. All runtime settings (credentials,
      bind address, output to mirror, H.264 backend, etc.) are read from
      ~/.config/hypr-rdp/config.toml, which can be generated by running the
      `hypr-rdp-setup` script installed by this module. Restart the service
      (`systemctl --user restart hypr-rdp`) after editing config.toml, since
      hypr-rdp only reads it at startup.
    '';
    type = types.submodule {
      options = {
        enable = mkEnableOption "hypr-rdp (RDP server for Hyprland)";

        package = mkOption {
          type = types.package;
          default = hypr-rdp-pkg;
          defaultText = literalMD "the hypr-rdp package with a corrected cargo vendor hash";
          description = ''
            hypr-rdp package to use. Defaults to a package built directly with
            the correct cargo vendor hash and the cursor-overlay fix.
          '';
        };
      };
    };
  };

  config = mkIf cfg.enable {
    home.packages = [
      cfg.package
      hypr-rdp-setup
    ];

    systemd.user.services.hypr-rdp = {
      Unit = {
        Description = "hypr-rdp (RDP server for Hyprland)";
        After = [ "graphical-session.target" ];
        PartOf = [ "graphical-session.target" ];
      };
      Service = {
        ExecStart = "${cfg.package}/bin/hypr-rdp";
        # The Wayland socket may not be ready the instant graphical-session.target
        # is reached (see the similar ashell workaround in hyprland.nix), so
        # retry on early failures.
        Restart = "always";
        RestartSec = 5;
      };
      Install = {
        WantedBy = [ "graphical-session.target" ];
      };
    };
  };
}