name: build-envs

on:
  push:
    paths:
    - darwin/**
    - workstation/**
    - flake.nix
    - .github/workflows/ci.yml
    - flake.lock
    - '!darwin/**.md'
    - '!workstation/**.md' 
    - '!**.md'
  schedule:
  - cron: '0 0 * * Thu'
  workflow_dispatch:

jobs:
  build-macos-env:
    name: Build/cache macOS Nix env
    runs-on: macos-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Install Nix
      uses: cachix/install-nix-action@v18

    - name: If scheduled or manually triggered, update inputs
      if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      run: |
        nix flake update
  
    - name: Build macos-desktop output 
      run: |
        # Create /run directory
        echo -e "run\tprivate/var/run" | sudo tee -a /etc/synthetic.conf >/dev/null
        /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t &>/dev/null || true
        # Build macos-desktop output
        nix build .#darwinConfigurations.macos-desktop-intel.system
   
    - name: If scheduled or manually triggered, add updated flake.lock, commit and push
      if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      uses: EndBug/add-and-commit@v9
      with:
        add: 'flake.lock'
        author_name: 'github-actions'
        author_email: 'github-actions@github.com' 
