name: build-darwin-env

on:
  push:
    branches:
    - 'master'
    paths:
    - darwin/**
    - .github/workflows/darwin.yml
    - '!darwin/**.md'
    - '!**.md'
  workflow_dispatch:

jobs:
  build-macos-env:
    name: Build macOS Nix env
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Setup Nix Magic Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build macos-desktop output
      run: |
        # Create /run directory
        echo -e "run\tprivate/var/run" | sudo tee -a /etc/synthetic.conf >/dev/null
        /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t &>/dev/null || true
        # Build macos-desktop output
        nix build .#darwinConfigurations.nix-mac-mini.system
