name: update-deploy-flake

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  update-deploy-flake:
    name: Update deploy flake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update deploy flake
        run: |
          nix flake update ./deploy

      - name: Commit update
        uses: EndBug/add-and-commit@v9
        with:
          add: 'deploy/flake.lock'
          author_name: 'github-actions'
          author_email: 'github-actions@github.com'
