name: build-linux-outputs

on:
  push:
    branches:
    - 'main'
    paths:
    - nixos/**
    - .github/workflows/linux.yml
    - home/linux.nix
    - home/desktop.nix
    - home/base.nix
    - home/linux/**
    - '!nixos/**.md'
    - '!home/**.md'
    - '!**.md'
    - flake.lock
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * Sat"

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: nixos-server-amd64
            runner: ubuntu-24.04
            build_cmd: nix build --accept-flake-config .#nixosConfigurations.nixos-server.config.system.build.toplevel

          - name: nixos-desktop-amd64
            runner: ubuntu-24.04
            build_cmd: nix build --accept-flake-config .#nixosConfigurations.nixos-desktop.config.system.build.toplevel

          - name: nixos-server-arm64
            runner: ubuntu-24.04-arm
            build_cmd: nix build --accept-flake-config .#nixosConfigurations.nixos-server.config.system.build.toplevel

          - name: nixos-desktop-arm64
            runner: ubuntu-24.04-arm
            build_cmd: nix build --accept-flake-config .#nixosConfigurations.nixos-desktop.config.system.build.toplevel

          - name: gaming-kernel-amd64
            runner: ubuntu-24.04
            build_cmd: nix build --accept-flake-config .#nixosConfigurations.nixos-gaming.config.boot.kernelPackages.kernel

          - name: gaming-gpu-driver-amd64
            runner: ubuntu-24.04
            build_cmd: nix build --accept-flake-config .#nixosConfigurations.nixos-gaming.config.hardware.nvidia.package

          - name: steam-deck-kernel-amd64
            runner: ubuntu-24.04
            build_cmd: nix build --accept-flake-config .#nixosConfigurations.steam-deck.config.boot.kernelPackages.kernel

          - name: steam-deck-mesa-amd64
            runner: ubuntu-24.04
            build_cmd: nix build --accept-flake-config .#nixosConfigurations.steam-deck.config.hardware.opengl.package

          - name: asahi-kernel-arm64
            runner: ubuntu-24.04-arm
            build_cmd: nix build --accept-flake-config .#nixosConfigurations.nixos-m1-mac-mini.config.boot.kernelPackages.kernel

          - name: asahi-mesa-arm64
            runner: ubuntu-24.04-arm
            build_cmd: nix build --accept-flake-config .#nixosConfigurations.nixos-m1-mac-mini.config.hardware.opengl.package

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Login to Tailnet
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        determinate: true

    - name: Set up binary cache
      env:
        ATTIC_PUBKEY: ${{ secrets.ATTIC_LINUX_PUBKEY }}
        ATTIC_CACHE: "http://attic/nixos"
      run: |
        sudo tee -a /etc/nix/nix.conf > /dev/null <<EOF
        extra-substituters = $ATTIC_CACHE
        extra-trusted-public-keys = $ATTIC_PUBKEY
        EOF

    - name: Free disk space
      uses: jlumbroso/free-disk-space@main

    - name: Configure attic
      env:
        ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
      run: |
        mkdir -p ~/.config/attic
        printf "default-server = \"kube\"\n\n[servers.kube]\nendpoint = \"http://attic\"\ntoken = \"$ATTIC_TOKEN\"" > ~/.config/attic/config.toml

    - name: Build ${{ matrix.name }}
      run: ${{ matrix.build_cmd }}

    - name: Push ${{ matrix.name }} to attic
      run: nix run nixpkgs#attic-client -- push nixos ./result*
