name: build-linux-outputs

on:
  push:
    branches:
    - 'master'
    paths:
    - nixos/**
    - home/**
    - .github/workflows/linux.yml
    - roles/**
    - '!nixos/**.md'
    - '!home/**.md'
    - '!**.md'
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * Sat"

jobs:
  build-linux-env:
    name: Build Linux outputs
    runs-on: [self-hosted, linux, x64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - name: Setup Nix Magic Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build Linux outputs
      run: |
        USER=docker nix run nixpkgs#cachix -- use heywoodlh-helix
        # Configure attic cache
        if ! grep 100.69.64.103 /etc/nix/nix.conf
        then
          echo "extra-substituters = http://100.69.64.103/nixos" | sudo tee -a /etc/nix/nix.conf
          echo "extra-trusted-public-keys = nixos:ZffGHlb0Ng3oXu8cLT9msyOB/datC4r+/K9nImONIec=" | sudo tee -a /etc/nix/nix.conf
        fi
        nix run nixpkgs#nixos-rebuild -- build --flake .#nixos-desktop-intel
        nix run nixpkgs#nixos-rebuild -- build --flake .#nixos-server-intel
        nix build .#homeConfigurations.heywoodlh.activationPackage --impure
        nix build .#homeConfigurations.heywoodlh-server.activationPackage --impure

  build-linux-arm64-env:
    name: Build Linux outputs
    runs-on: [self-hosted, linux, arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - name: Setup Nix Magic Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build Linux outputs
      run: |
        USER=docker nix run nixpkgs#cachix -- use heywoodlh-helix
        # Configure attic cache
        if ! grep 100.69.64.103 /etc/nix/nix.conf
        then
          echo "extra-substituters = http://100.69.64.103/nixos" | sudo tee -a /etc/nix/nix.conf
          echo "extra-trusted-public-keys = nixos:ZffGHlb0Ng3oXu8cLT9msyOB/datC4r+/K9nImONIec=" | sudo tee -a /etc/nix/nix.conf
        fi
        nix run nixpkgs#nixos-rebuild -- build --flake .#nixos-arm64-test
        nix run nixpkgs#nixos-rebuild -- build --flake .#nixos-mac-mini
        nix build .#homeConfigurations.heywoodlh.activationPackage --impure
        nix build .#homeConfigurations.heywoodlh-server.activationPackage --impure
