name: macos-ci

on:
  push:
    paths:
    - darwin/**
    - flake.nix
    - .github/workflows/macos-ci.yml
    - flake.lock
    - '!darwin/**.md'
  workflow_dispatch:

jobs:
  build-macos-env:
    name: Build/cache macOS Nix env
    runs-on: macos-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Install Nix
      uses: cachix/install-nix-action@v18
  
    - name: Build macos-desktop output 
      run: |
        # Create /run directory
        echo -e "run\tprivate/var/run" | sudo tee -a /etc/synthetic.conf >/dev/null
        /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t &>/dev/null || true
        # Build macos-desktop output
        nix build .#darwinConfigurations.macos-desktop-intel.system
